grails-app/domain/new1/Timesheet.groovy
package new1

class Timesheet {
	Date fromdate;
	Date todate;
	String project;
	String task;
	String description;
	int work_hour;
	Employee employee;
    static constraints = {
    	fromdate(blank:false)
    	todate(blank:false)
    	task(blank:false)
    	description(blank:false)
    	work_hour(blank:false)
    }	
}

grails-app/controllers/new1/TimesheetController.groovy
package new1



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import java.text.DateFormat;
    import java.text.SimpleDateFormat;
    import java.util.Date;

@Transactional(readOnly = true)
class TimesheetController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Timesheet.list(params), model:[timesheetInstanceCount: Timesheet.count()]
    }

    def show(Timesheet timesheetInstance) {
        respond timesheetInstance
    }

    def create() {
        respond new Timesheet(params)
    }

    @Transactional
    def save() {
        System.out.println(params.fromdate+params.todate+params.task+params.description+params.workhour);
       if(params.fromdate.isEmpty() || params.todate.isEmpty() || params.task.isEmpty() || params.description.isEmpty() || params.workhour.isEmpty()){
            if(params.fromdate.isEmpty()){
                System.out.println("ent1");    
                flash.message="from"
            }
            else{
                if(params.todate.isEmpty())
                    flash.message="to"
                else if(params.task.isEmpty())
                    flash.message="task"
                else if(params.description.isEmpty())
                    flash.message="des"
                else
                    flash.message="work"
            }
            System.out.println("ent");
            redirect(controller:"Employee" ,action:"time")
            flash.message=''
            return
        }
        else{
            System.out.println("hari___BOL")
            def newTs = new Timesheet();
            SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
            Date startDate, endDate;
            startDate = sdf.parse(params.fromdate);
            endDate = sdf.parse(params.todate);
            newTs.fromdate =  startDate 
            newTs.todate = endDate;
            newTs.project= params.project;
            newTs.task = params.task
            newTs.description = params.description;
            int xyz=Integer.parseInt(params.workhour)
            newTs.work_hour = xyz;
            newTs.employee = Employee.findByUsername(params.username);
            if(newTs.save(flush:true)){
                flash.message="submitted"
                redirect(controller:"Employee", action:"time");
            }
            else{
                render('not saved')
                  
            }

        }
    }

    def edit(Timesheet timesheetInstance) {
        respond timesheetInstance
    }

    @Transactional
    def update(Timesheet timesheetInstance) {
        if (timesheetInstance == null) {
            notFound()
            return
        }

        if (timesheetInstance.hasErrors()) {
            respond timesheetInstance.errors, view:'edit'
            return
        }

        timesheetInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Timesheet.label', default: 'Timesheet'), timesheetInstance.id])
                redirect timesheetInstance
            }
            '*'{ respond timesheetInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Timesheet timesheetInstance) {

        if (timesheetInstance == null) {
            notFound()
            return
        }

        timesheetInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Timesheet.label', default: 'Timesheet'), timesheetInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'timesheet.label', default: 'Timesheet'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/timesheet/_form.gsp
<%@ page import="new1.Timesheet" %>



<div class="fieldcontain ${hasErrors(bean: timesheetInstance, field: 'fromdate', 'error')} required">
	<label for="fromdate">
		<g:message code="timesheet.fromdate.label" default="Fromdate" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="fromdate" required="" value="${timesheetInstance?.fromdate}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: timesheetInstance, field: 'todate', 'error')} required">
	<label for="todate">
		<g:message code="timesheet.todate.label" default="Todate" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="todate" required="" value="${timesheetInstance?.todate}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: timesheetInstance, field: 'task', 'error')} required">
	<label for="task">
		<g:message code="timesheet.task.label" default="Task" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="task" required="" value="${timesheetInstance?.task}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: timesheetInstance, field: 'description', 'error')} required">
	<label for="description">
		<g:message code="timesheet.description.label" default="Description" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="description" required="" value="${timesheetInstance?.description}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: timesheetInstance, field: 'work_hour', 'error')} required">
	<label for="work_hour">
		<g:message code="timesheet.work_hour.label" default="Workhour" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="work_hour" required="" value="${timesheetInstance?.work_hour}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: timesheetInstance, field: 'employee', 'error')} required">
	<label for="employee">
		<g:message code="timesheet.employee.label" default="Employee" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="employee" name="employee.id" from="${new1.Employee.list()}" optionKey="id" required="" value="${timesheetInstance?.employee?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: timesheetInstance, field: 'project', 'error')} required">
	<label for="project">
		<g:message code="timesheet.project.label" default="Project" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="project" required="" value="${timesheetInstance?.project}"/>

</div>

grails-app/views/timesheet/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'timesheet.label', default: 'Timesheet')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-timesheet" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-timesheet" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${timesheetInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${timesheetInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:timesheetInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/timesheet/edit.gsp
<%@ page import="new1.Timesheet" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'timesheet.label', default: 'Timesheet')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-timesheet" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-timesheet" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${timesheetInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${timesheetInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:timesheetInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${timesheetInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/timesheet/index.gsp
<%@ page import="new1.Timesheet" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'timesheet.label', default: 'Timesheet')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-timesheet" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-timesheet" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="fromdate" title="${message(code: 'timesheet.fromdate.label', default: 'Fromdate')}" />
					
						<g:sortableColumn property="todate" title="${message(code: 'timesheet.todate.label', default: 'Todate')}" />
					
						<g:sortableColumn property="task" title="${message(code: 'timesheet.task.label', default: 'Task')}" />
					
						<g:sortableColumn property="description" title="${message(code: 'timesheet.description.label', default: 'Description')}" />
					
						<g:sortableColumn property="work_hour" title="${message(code: 'timesheet.work_hour.label', default: 'Workhour')}" />
					
						<th><g:message code="timesheet.employee.label" default="Employee" /></th>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${timesheetInstanceList}" status="i" var="timesheetInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${timesheetInstance.id}">${fieldValue(bean: timesheetInstance, field: "fromdate")}</g:link></td>
					
						<td>${fieldValue(bean: timesheetInstance, field: "todate")}</td>
					
						<td>${fieldValue(bean: timesheetInstance, field: "task")}</td>
					
						<td>${fieldValue(bean: timesheetInstance, field: "description")}</td>
					
						<td>${fieldValue(bean: timesheetInstance, field: "work_hour")}</td>
					
						<td>${fieldValue(bean: timesheetInstance, field: "employee")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${timesheetInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/timesheet/show.gsp
<%@ page import="new1.Timesheet" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'timesheet.label', default: 'Timesheet')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-timesheet" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-timesheet" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list timesheet">
			
				<g:if test="${timesheetInstance?.fromdate}">
				<li class="fieldcontain">
					<span id="fromdate-label" class="property-label"><g:message code="timesheet.fromdate.label" default="Fromdate" /></span>
					
						<span class="property-value" aria-labelledby="fromdate-label"><g:fieldValue bean="${timesheetInstance}" field="fromdate"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${timesheetInstance?.todate}">
				<li class="fieldcontain">
					<span id="todate-label" class="property-label"><g:message code="timesheet.todate.label" default="Todate" /></span>
					
						<span class="property-value" aria-labelledby="todate-label"><g:fieldValue bean="${timesheetInstance}" field="todate"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${timesheetInstance?.task}">
				<li class="fieldcontain">
					<span id="task-label" class="property-label"><g:message code="timesheet.task.label" default="Task" /></span>
					
						<span class="property-value" aria-labelledby="task-label"><g:fieldValue bean="${timesheetInstance}" field="task"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${timesheetInstance?.description}">
				<li class="fieldcontain">
					<span id="description-label" class="property-label"><g:message code="timesheet.description.label" default="Description" /></span>
					
						<span class="property-value" aria-labelledby="description-label"><g:fieldValue bean="${timesheetInstance}" field="description"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${timesheetInstance?.work_hour}">
				<li class="fieldcontain">
					<span id="work_hour-label" class="property-label"><g:message code="timesheet.work_hour.label" default="Workhour" /></span>
					
						<span class="property-value" aria-labelledby="work_hour-label"><g:fieldValue bean="${timesheetInstance}" field="work_hour"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${timesheetInstance?.employee}">
				<li class="fieldcontain">
					<span id="employee-label" class="property-label"><g:message code="timesheet.employee.label" default="Employee" /></span>
					
						<span class="property-value" aria-labelledby="employee-label"><g:link controller="employee" action="show" id="${timesheetInstance?.employee?.id}">${timesheetInstance?.employee?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${timesheetInstance?.project}">
				<li class="fieldcontain">
					<span id="project-label" class="property-label"><g:message code="timesheet.project.label" default="Project" /></span>
					
						<span class="property-value" aria-labelledby="project-label"><g:fieldValue bean="${timesheetInstance}" field="project"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:timesheetInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${timesheetInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>