grails-app/domain/new1/SalarySheet.groovy
package new1

class SalarySheet {
	
	static belongsTo = [employee:Employee]
    static constraints = {
    }
}

grails-app/controllers/new1/SalarySheetController.groovy
package new1
import java.net.InetAddress;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;

import org.apache.commons.net.ntp.NTPUDPClient; 
import org.apache.commons.net.ntp.TimeInfo;

import java.io.File;
import java.io.FileInputStream;
import java.util.Date;

import jxl.Workbook;
import jxl.format.VerticalAlignment;
import jxl.write.*;


import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional


import java.net.InetAddress;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.GregorianCalendar;

import org.apache.commons.net.ntp.NTPUDPClient; 
import org.apache.commons.net.ntp.TimeInfo;

import java.io.File;
import java.io.FileInputStream;
import java.util.Date;

import jxl.Workbook;
import jxl.format.VerticalAlignment;
import jxl.write.*;

@Transactional(readOnly = true)
class SalarySheetController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]


    WritableWorkbook workbook;
    WritableSheet sheet;
    WritableFont cellFont;
    WritableCellFormat newCellFormat;
    WritableCellFormat cellFormat;
    String yearDuration;
    String yearQueried;
    SimpleDateFormat sdfDate;
    Date currDate;
    String strDate;
    Date dateOfJoin;
    int startMonth;
    int multiFactor;
    String str_Date;
    SimpleDateFormat formatter;
    Date startDate;
    Date endDate;
    long actualDiff;
    long diff;
    int noOfMonths;
    SimpleDateFormat monthFormat;
    SimpleDateFormat yearFormat;
    int currYear;
    int yearOfJoin;
    ArrayList<String> months;
    ArrayList<String> years;
    int lastColumn;
    int noOfSalComp;
    ArrayList<String> salComp;
    int salaryStartRow;
    int workingMonths;
    double[] salStruct;
    double totalSalPerMonth;
    int row;
    double grossTHComp;
    float employeePF;
    int rowGrossDed;
    float totalGrossDed;
    double netPayBeforeTaxes;
    int rowTax;
    WritableCellFormat boldBlueCellFormat;
    WritableCellFormat noBoldBlackRightCellFormat;
    WritableCellFormat noBoldBlackLeftCellFormat;
    double professionTax;
    double[] inTaxPerMonth;
    double totInTax;
    double totInTaxYTD;
    double[] netPayPerMonth;
    double totNetPayAfterTaxes;
    double totNetPayAfterTaxesYTD;
    int month;
    Label lable;



//  this function is just for purpose of generating random date of joining till the time the date is not taken from database
     Date randDateOfJoin() throws Exception{
            GregorianCalendar gc = new GregorianCalendar();
            int year = randBetween(1980, 2015);
            gc.set(gc.YEAR, year);
            int dayOfYear = randBetween(1, gc.getActualMaximum(gc.DAY_OF_YEAR));
            gc.set(gc.DAY_OF_YEAR, dayOfYear);
            String dateOfJoin_Str = (gc.get(gc.YEAR) + "-" + (gc.get(gc.MONTH) + 1) + "-" + gc.get(gc.DAY_OF_MONTH));
            System.out.println(dateOfJoin_Str);
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-M-d");
            Date dateOfJoin = dateFormat.parse(dateOfJoin_Str);
            return dateOfJoin;
        }

        static int randBetween(int start, int end) {
            return start + (int)Math.round(Math.random() * (end - start));
        }
    
    Date currentDate() throws Exception
    {       
        String TIME_SERVER = "time-a.nist.gov";   
        NTPUDPClient timeClient = new NTPUDPClient();
        InetAddress inetAddress = InetAddress.getByName(TIME_SERVER);
        TimeInfo timeInfo = timeClient.getTime(inetAddress);
        long returnTime = timeInfo.getReturnTime();
        Date time = new Date(returnTime);
        return time;
    }  

    def generateSalarySheet()
    {
        println 'hari'
        println 'harihari'
        response.setContentType('application/vnd.ms-excel')
        response.setHeader('Content-Disposition', 'Attachment;Filename="salary_sheet.xls"')
        try
        {
             workbook = Workbook.createWorkbook(response.outputStream);
             sheet = workbook.createSheet("SalarySheet", 0);
             sheet.getSettings().setProtected(true);
             
             sheet.setColumnView(0, 33);
             for(int i=1;i<=15;i++)
            {
                sheet.setColumnView(i, 23);
            }
                
                
             cellFont = new WritableFont(WritableFont.TIMES, 16);
            cellFont.setBoldStyle(WritableFont.BOLD);
            cellFont.setColour(Colour.BLACK);

             newCellFormat = new WritableCellFormat(cellFont);
            newCellFormat.setBackground(Colour.WHITE);
            newCellFormat.setAlignment(Alignment.CENTRE);
            newCellFormat.setVerticalAlignment(VerticalAlignment.CENTRE);
            

            cellFormat = new WritableCellFormat(newCellFormat);
            cellFormat.setBorder(Border.NONE, BorderLineStyle.THICK);
            
//          get year duration
            yearDuration="Apr 15 - Mar 16"; 
            
            yearQueried = yearDuration.substring(4, 6);   // 15 in this case
                    
            sheet.mergeCells(0, 0,7,0);
             lable = new Label(0, 0, "Salary sheet for the year "+yearDuration, cellFormat);
            sheet.addCell(lable);
            
            sheet.mergeCells(8, 0,13,0);
            lable = new Label(8, 0, "", cellFormat);
            sheet.addCell(lable);
            
            sheet.mergeCells(0,1, 13,1);
            lable = new Label(0, 1, "", cellFormat);
            sheet.addCell(lable);
            
            cellFont = new WritableFont(WritableFont.TIMES, 11);
            cellFont.setBoldStyle(WritableFont.BOLD);
            cellFont.setColour(Colour.BLACK);

            newCellFormat = new WritableCellFormat(cellFont);
            newCellFormat.setBackground(Colour.WHITE);
            newCellFormat.setAlignment(Alignment.CENTRE);
            newCellFormat.setVerticalAlignment(VerticalAlignment.CENTRE);
            

            cellFormat = new WritableCellFormat(newCellFormat);
            cellFormat.setBorder(Border.ALL, BorderLineStyle.THICK);
            cellFormat.setAlignment(Alignment.LEFT);
            
            lable = new Label(0, 2, "Employee ID ", cellFormat);
            sheet.addCell(lable);

            def emp = session.emp
            def profile = Profile.findByEmployeeAndYear(emp)

            String id=String.valueOf(emp.id)
            sheet.mergeCells(1, 2, 2, 2);
            lable = new Label(1, 2, id, cellFormat);
            sheet.addCell(lable);
                        
            lable = new Label(0, 3, "Name ", cellFormat);
            sheet.addCell(lable);
            String name=profile.first+" "+profile.last;
            sheet.mergeCells(1, 3, 2, 3);
            lable = new Label(1, 3, name, cellFormat);
            sheet.addCell(lable);
                       
            lable = new Label(0, 4, "Organization ", cellFormat);
            sheet.addCell(lable);
            String org=profile.organization;
            sheet.mergeCells(1, 4, 2, 4);
            lable = new Label(1, 4, org, cellFormat);
            sheet.addCell(lable);

            lable = new Label(0, 5, "Date of Report Generation ", cellFormat);
            sheet.addCell(lable);
            
//          getting current date and time
                
            sdfDate = new SimpleDateFormat("dd-MMM-yyyy HH:mm:ss");      //dd/MM/yyyy
            currDate = currentDate();   
            strDate = sdfDate.format(currDate);
            sheet.mergeCells(1, 5, 2, 5);
            lable = new Label(1, 5, strDate, cellFormat);
            sheet.addCell(lable);

            lable = new Label(0, 6, "PAN", cellFormat);
            sheet.addCell(lable);
            String pan=profile.panno;
            sheet.mergeCells(1, 6, 2, 6);
            lable = new Label(1, 6, pan, cellFormat);
            sheet.addCell(lable);
            
//          merging right empty side
            
            cellFormat = new WritableCellFormat(newCellFormat);
            cellFormat.setBorder(Border.NONE, BorderLineStyle.THICK);
            
            sheet.mergeCells(3,2,13,6);
            lable = new Label(3, 2, "", cellFormat);
            sheet.addCell(lable);
            
//          merging rows 7,8,9
            
            sheet.mergeCells(0,7,13,9);
            lable = new Label(0, 7, "", cellFormat);
            sheet.addCell(lable);
            
            cellFont = new WritableFont(WritableFont.TIMES, 12);
            cellFont.setBoldStyle(WritableFont.BOLD);
            cellFont.setColour(Colour.BLACK);

            newCellFormat = new WritableCellFormat(cellFont);
            newCellFormat.setBackground(Colour.LIGHT_BLUE);
            newCellFormat.setAlignment(Alignment.CENTRE);
            newCellFormat.setVerticalAlignment(VerticalAlignment.CENTRE);
            
            cellFormat = new WritableCellFormat(newCellFormat);
            cellFormat.setBorder(Border.ALL, BorderLineStyle.THICK);
            
            sheet.mergeCells(0,10,0,11);
            lable = new Label(0, 10, "Compensation/ Deduction", cellFormat);
            sheet.addCell(lable);
            
            sheet.mergeCells(1,10,1,11);
            lable = new Label(1, 10, "Annual", cellFormat);
            sheet.addCell(lable);
            
//          getting the Date of join from Profile class
            dateOfJoin = profile.date
            
//          startMonth of the current year
            startMonth = 0;  // 0 means april
            
            
//          if difference between current date and 1 april is less than diff b/w 31 mar and 1 apr, 
//              if current year is year of joining also, then noOfMonths = currMonth-monthOfJoin+1 & startMonth=monthOfJoin
//              else  noOfMonths=currMonth-april+1 & startMonth = april

grails-app/views/salarySheet/_form.gsp
<%@ page import="new1.SalarySheet" %>

grails-app/views/salarySheet/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'salarySheet.label', default: 'SalarySheet')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-salarySheet" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-salarySheet" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${salarySheetInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${salarySheetInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:salarySheetInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/salarySheet/edit.gsp
<%@ page import="new1.SalarySheet" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'salarySheet.label', default: 'SalarySheet')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-salarySheet" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-salarySheet" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${salarySheetInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${salarySheetInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:salarySheetInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${salarySheetInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/salarySheet/index.gsp
<%@ page import="new1.SalarySheet" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'salarySheet.label', default: 'SalarySheet')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-salarySheet" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-salarySheet" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${salarySheetInstanceList}" status="i" var="salarySheetInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${salarySheetInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/salarySheet/show.gsp
<%@ page import="new1.SalarySheet" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'salarySheet.label', default: 'SalarySheet')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-salarySheet" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-salarySheet" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list salarySheet">
			
			</ol>
			<g:form url="[resource:salarySheetInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${salarySheetInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>