grails-app/domain/new1/Project_task.groovy
package new1

class Project_task {
	String name
	static belongsTo = [project : Project]
	static hasMany = [ sub_task : Project_subtask]
	Date start_date

    static constraints = {
    }
    
}

grails-app/controllers/new1/Project_taskController.groovy
package new1



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional
import java.text.DateFormat
import java.text.SimpleDateFormat

//@Transactional(readOnly = true)
class Project_taskController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE" , deleting:"GET" , testing:"GET"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Project_task.list(params), model:[taskInstanceCount: Project_task.count()]
    }

    def show(Project_task taskInstance) {
        respond taskInstance
    }

    def create() {
        respond new Project_task(params)
    }

    def testing()
    {
        System.out.println("inside")
        
        java.util.Date fecha1 = new java.util.Date(params.start_time);
        DateFormat formatter = new SimpleDateFormat("EEE MMM dd HH:mm:ss Z yyyy");
        
        Date date2
        
        date2 = (Date)formatter.parse(fecha1.toString());
        def sample=new Project_task();
        def xyz=Project.findAllByProject_nameAndManager(params.project_name, session.manage)  
        
        sample.start_date=date2
        sample.name=params.task_name
        
        System.out.println (date2)
        
        
        
        sample.save()
        xyz[0].addToTasks(sample)
        sample.save(flush:true)
        System.out.println(xyz[0])
System.out.println("done it")
    }
    def deleting()
    {
        System.out.println("inside")
        def xyz=Project_task.findAllByName(params.task_name)
        System.out.println(xyz[0])
        xyz[0].delete(flush:true)
        System.out.println("done it")
    }

    @Transactional
    def save() {
        if(params == null){
            render(controller:"Employee" , view:"home")
            flash.message=''
            return
        }
        def task =Project_task.findByProject_task(params.task);
        if(task!=null){
            flash.message="task already exist"
            render(controller:"Employee" , view:"home")
        }
        else{
            def newt = new Project_task();
            newt.task=params.task
            newt.project=Project.findByName(params.project);
            def a = Manager.findByUsername(params.manager);
            //def ad = Project_task.findByProject_id(params.project.id)
            def c = Project_task.createCriteria().list{
                project {
                    eq('id' , newt.project.id)
                }
            }
            System.out.println(c);
            //newt.manager_id=params.manager_id;
            //System.out.println(params.manager_id)
            //newt.manager=Manager.getByid(params.manager_id)
            if(newt.save(flush:true)){
               flash.message="task created"
                redirect(controller:"Manager", action:"abc", params:[username:a.username]);
            }
            else{
                flash.message="Please enter valid data"
                render('Not saved')
            }
        }
    }

    def edit(Project_task taskInstance) {
        respond taskInstance
    }

    @Transactional
    def update(Project_task taskInstance) {
        if (taskInstance == null) {
            notFound()
            return
        }

        if (taskInstance.hasErrors()) {
            respond taskInstance.errors, view:'edit'
            return
        }

        taskInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Project_task.label', default: 'Project_task'), taskInstance.id])
                redirect taskInstance
            }
            '*'{ respond taskInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Project_task taskInstance) {

        if (taskInstance == null) {
            notFound()
            return
        }

        taskInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Project_task.label', default: 'Project_task'), taskInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'task.label', default: 'Project_task'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/project_task/_form.gsp
<%@ page import="new1.Project_task" %>



<div class="fieldcontain ${hasErrors(bean: project_taskInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="project_task.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" required="" value="${project_taskInstance?.name}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: project_taskInstance, field: 'project', 'error')} required">
	<label for="project">
		<g:message code="project_task.project.label" default="Project" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="project" name="project.id" from="${new1.Project.list()}" optionKey="id" required="" value="${project_taskInstance?.project?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: project_taskInstance, field: 'start_date', 'error')} required">
	<label for="start_date">
		<g:message code="project_task.start_date.label" default="Startdate" />
		<span class="required-indicator">*</span>
	</label>
	<g:datePicker name="start_date" precision="day"  value="${project_taskInstance?.start_date}"  />

</div>

<div class="fieldcontain ${hasErrors(bean: project_taskInstance, field: 'sub_task', 'error')} ">
	<label for="sub_task">
		<g:message code="project_task.sub_task.label" default="Subtask" />
		
	</label>
	
<ul class="one-to-many">
<g:each in="${project_taskInstance?.sub_task?}" var="s">
    <li><g:link controller="project_subtask" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></li>
</g:each>
<li class="add">
<g:link controller="project_subtask" action="create" params="['project_task.id': project_taskInstance?.id]">${message(code: 'default.add.label', args: [message(code: 'project_subtask.label', default: 'Project_subtask')])}</g:link>
</li>
</ul>


</div>

grails-app/views/project_task/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'project_task.label', default: 'Project_task')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-project_task" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-project_task" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${project_taskInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${project_taskInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:project_taskInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/project_task/edit.gsp
<%@ page import="new1.Project_task" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'project_task.label', default: 'Project_task')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-project_task" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-project_task" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${project_taskInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${project_taskInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:project_taskInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${project_taskInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/project_task/index.gsp
<%@ page import="new1.Project_task" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'project_task.label', default: 'Project_task')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-project_task" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-project_task" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<g:sortableColumn property="name" title="${message(code: 'project_task.name.label', default: 'Name')}" />
					
						<th><g:message code="project_task.project.label" default="Project" /></th>
					
						<g:sortableColumn property="start_date" title="${message(code: 'project_task.start_date.label', default: 'Startdate')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${project_taskInstanceList}" status="i" var="project_taskInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${project_taskInstance.id}">${fieldValue(bean: project_taskInstance, field: "name")}</g:link></td>
					
						<td>${fieldValue(bean: project_taskInstance, field: "project")}</td>
					
						<td><g:formatDate date="${project_taskInstance.start_date}" /></td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${project_taskInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/project_task/show.gsp
<%@ page import="new1.Project_task" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'project_task.label', default: 'Project_task')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-project_task" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-project_task" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list project_task">
			
				<g:if test="${project_taskInstance?.name}">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="project_task.name.label" default="Name" /></span>
					
						<span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${project_taskInstance}" field="name"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${project_taskInstance?.project}">
				<li class="fieldcontain">
					<span id="project-label" class="property-label"><g:message code="project_task.project.label" default="Project" /></span>
					
						<span class="property-value" aria-labelledby="project-label"><g:link controller="project" action="show" id="${project_taskInstance?.project?.id}">${project_taskInstance?.project?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${project_taskInstance?.start_date}">
				<li class="fieldcontain">
					<span id="start_date-label" class="property-label"><g:message code="project_task.start_date.label" default="Startdate" /></span>
					
						<span class="property-value" aria-labelledby="start_date-label"><g:formatDate date="${project_taskInstance?.start_date}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${project_taskInstance?.sub_task}">
				<li class="fieldcontain">
					<span id="sub_task-label" class="property-label"><g:message code="project_task.sub_task.label" default="Subtask" /></span>
					
						<g:each in="${project_taskInstance.sub_task}" var="s">
						<span class="property-value" aria-labelledby="sub_task-label"><g:link controller="project_subtask" action="show" id="${s.id}">${s?.encodeAsHTML()}</g:link></span>
						</g:each>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:project_taskInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${project_taskInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>