grails-app/domain/new1/Rentdetails.groovy
package new1

class Rentdetails {
	String from_date;
	String to_date;
	Integer total_rent;
	String location;
	Boolean ismetro;
	static belongsTo = [employee: Employee];
    static constraints = {
    }
}

grails-app/controllers/new1/RentdetailsController.groovy
package new1



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class RentdetailsController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond Rentdetails.list(params), model:[rentdetailsInstanceCount: Rentdetails.count()]
    }

    def show(Rentdetails rentdetailsInstance) {
        respond rentdetailsInstance
    }

    def create() {
        respond new Rentdetails(params)
    }

    @Transactional
    def save() {
         System.out.println("")
       if(params == null){
            redirect(controller:"Employee", action:"dec");
            flash.message=''
            return
        }
        def mall = Rentdetails.findByLocation(params.location)
        if(mall){
            flash.message="alredy given";
            redirect(controller:"Employee", action:"dec");
        }
        else{
            def newM = new Rentdetails();
            int b = params.totalrent.toInteger();
            newM.total_rent=b
            System.out.println(b)
            String from=params.fromdate.toString()
            String to=params.todate.toString()
            newM.from_date= from
            newM.to_date= to
            System.out.println( newM.from_date)

            String loc=params.location.toString();
             System.out.println(loc)
             newM.location=loc 
              println params.ismetro as boolean
             newM.ismetro=params.ismetro as boolean
              System.out.println()
            newM.employee = Employee.findByUsername(params.username)
            System.out.println(params.username)
            if(newM.save(flush:true)){
                flash.message =='SUCCESS! Rentdetails submitted '
                println 'harihari'
               redirect(controller:"Employee", action:"dec");
            }
            else{
                 flash.message =='FAILED! Rentdetails not submitted'
                 redirect(controller:"Employee", action:"dec");
            }
        }
    }

    def edit(Rentdetails rentdetailsInstance) {
        respond rentdetailsInstance
    }

    @Transactional
    def update(Rentdetails rentdetailsInstance) {
        if (rentdetailsInstance == null) {
            notFound()
            return
        }

        if (rentdetailsInstance.hasErrors()) {
            respond rentdetailsInstance.errors, view:'edit'
            return
        }

        rentdetailsInstance.save flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'Rentdetails.label', default: 'Rentdetails'), rentdetailsInstance.id])
                redirect rentdetailsInstance
            }
            '*'{ respond rentdetailsInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(Rentdetails rentdetailsInstance) {

        if (rentdetailsInstance == null) {
            notFound()
            return
        }

        rentdetailsInstance.delete flush:true

        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'Rentdetails.label', default: 'Rentdetails'), rentdetailsInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'rentdetails.label', default: 'Rentdetails'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/rentdetails/_form.gsp
<%@ page import="new1.Rentdetails" %>



<div class="fieldcontain ${hasErrors(bean: rentdetailsInstance, field: 'employee', 'error')} required">
	<label for="employee">
		<g:message code="rentdetails.employee.label" default="Employee" />
		<span class="required-indicator">*</span>
	</label>
	<g:select id="employee" name="employee.id" from="${new1.Employee.list()}" optionKey="id" required="" value="${rentdetailsInstance?.employee?.id}" class="many-to-one"/>

</div>

<div class="fieldcontain ${hasErrors(bean: rentdetailsInstance, field: 'from_date', 'error')} required">
	<label for="from_date">
		<g:message code="rentdetails.from_date.label" default="Fromdate" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="from_date" required="" value="${rentdetailsInstance?.from_date}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: rentdetailsInstance, field: 'ismetro', 'error')} ">
	<label for="ismetro">
		<g:message code="rentdetails.ismetro.label" default="Ismetro" />
		
	</label>
	<g:checkBox name="ismetro" value="${rentdetailsInstance?.ismetro}" />

</div>

<div class="fieldcontain ${hasErrors(bean: rentdetailsInstance, field: 'location', 'error')} required">
	<label for="location">
		<g:message code="rentdetails.location.label" default="Location" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="location" required="" value="${rentdetailsInstance?.location}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: rentdetailsInstance, field: 'to_date', 'error')} required">
	<label for="to_date">
		<g:message code="rentdetails.to_date.label" default="Todate" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="to_date" required="" value="${rentdetailsInstance?.to_date}"/>

</div>

<div class="fieldcontain ${hasErrors(bean: rentdetailsInstance, field: 'total_rent', 'error')} required">
	<label for="total_rent">
		<g:message code="rentdetails.total_rent.label" default="Totalrent" />
		<span class="required-indicator">*</span>
	</label>
	<g:field name="total_rent" type="number" value="${rentdetailsInstance.total_rent}" required=""/>

</div>

grails-app/views/rentdetails/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'rentdetails.label', default: 'Rentdetails')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#create-rentdetails" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-rentdetails" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${rentdetailsInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${rentdetailsInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:rentdetailsInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/rentdetails/edit.gsp
<%@ page import="new1.Rentdetails" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'rentdetails.label', default: 'Rentdetails')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#edit-rentdetails" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-rentdetails" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${rentdetailsInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${rentdetailsInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:rentdetailsInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${rentdetailsInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/rentdetails/index.gsp
<%@ page import="new1.Rentdetails" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'rentdetails.label', default: 'Rentdetails')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#list-rentdetails" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-rentdetails" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
					
						<th><g:message code="rentdetails.employee.label" default="Employee" /></th>
					
						<g:sortableColumn property="from_date" title="${message(code: 'rentdetails.from_date.label', default: 'Fromdate')}" />
					
						<g:sortableColumn property="ismetro" title="${message(code: 'rentdetails.ismetro.label', default: 'Ismetro')}" />
					
						<g:sortableColumn property="location" title="${message(code: 'rentdetails.location.label', default: 'Location')}" />
					
						<g:sortableColumn property="to_date" title="${message(code: 'rentdetails.to_date.label', default: 'Todate')}" />
					
						<g:sortableColumn property="total_rent" title="${message(code: 'rentdetails.total_rent.label', default: 'Totalrent')}" />
					
					</tr>
				</thead>
				<tbody>
				<g:each in="${rentdetailsInstanceList}" status="i" var="rentdetailsInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
					
						<td><g:link action="show" id="${rentdetailsInstance.id}">${fieldValue(bean: rentdetailsInstance, field: "employee")}</g:link></td>
					
						<td>${fieldValue(bean: rentdetailsInstance, field: "from_date")}</td>
					
						<td><g:formatBoolean boolean="${rentdetailsInstance.ismetro}" /></td>
					
						<td>${fieldValue(bean: rentdetailsInstance, field: "location")}</td>
					
						<td>${fieldValue(bean: rentdetailsInstance, field: "to_date")}</td>
					
						<td>${fieldValue(bean: rentdetailsInstance, field: "total_rent")}</td>
					
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${rentdetailsInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/rentdetails/show.gsp
<%@ page import="new1.Rentdetails" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="main">
		<g:set var="entityName" value="${message(code: 'rentdetails.label', default: 'Rentdetails')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<a href="#show-rentdetails" class="skip" tabindex="-1"><g:message code="default.link.skip.label" default="Skip to content&hellip;"/></a>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-rentdetails" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list rentdetails">
			
				<g:if test="${rentdetailsInstance?.employee}">
				<li class="fieldcontain">
					<span id="employee-label" class="property-label"><g:message code="rentdetails.employee.label" default="Employee" /></span>
					
						<span class="property-value" aria-labelledby="employee-label"><g:link controller="employee" action="show" id="${rentdetailsInstance?.employee?.id}">${rentdetailsInstance?.employee?.encodeAsHTML()}</g:link></span>
					
				</li>
				</g:if>
			
				<g:if test="${rentdetailsInstance?.from_date}">
				<li class="fieldcontain">
					<span id="from_date-label" class="property-label"><g:message code="rentdetails.from_date.label" default="Fromdate" /></span>
					
						<span class="property-value" aria-labelledby="from_date-label"><g:fieldValue bean="${rentdetailsInstance}" field="from_date"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${rentdetailsInstance?.ismetro}">
				<li class="fieldcontain">
					<span id="ismetro-label" class="property-label"><g:message code="rentdetails.ismetro.label" default="Ismetro" /></span>
					
						<span class="property-value" aria-labelledby="ismetro-label"><g:formatBoolean boolean="${rentdetailsInstance?.ismetro}" /></span>
					
				</li>
				</g:if>
			
				<g:if test="${rentdetailsInstance?.location}">
				<li class="fieldcontain">
					<span id="location-label" class="property-label"><g:message code="rentdetails.location.label" default="Location" /></span>
					
						<span class="property-value" aria-labelledby="location-label"><g:fieldValue bean="${rentdetailsInstance}" field="location"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${rentdetailsInstance?.to_date}">
				<li class="fieldcontain">
					<span id="to_date-label" class="property-label"><g:message code="rentdetails.to_date.label" default="Todate" /></span>
					
						<span class="property-value" aria-labelledby="to_date-label"><g:fieldValue bean="${rentdetailsInstance}" field="to_date"/></span>
					
				</li>
				</g:if>
			
				<g:if test="${rentdetailsInstance?.total_rent}">
				<li class="fieldcontain">
					<span id="total_rent-label" class="property-label"><g:message code="rentdetails.total_rent.label" default="Totalrent" /></span>
					
						<span class="property-value" aria-labelledby="total_rent-label"><g:fieldValue bean="${rentdetailsInstance}" field="total_rent"/></span>
					
				</li>
				</g:if>
			
			</ol>
			<g:form url="[resource:rentdetailsInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${rentdetailsInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>